trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # Free hosted agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      cd front
      npm install
    displayName: 'Install Angular CLI & Dependencies'

  - script: |
      cd front
      ng build shopfer --configuration production
    displayName: 'Build Angular Project'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'front/dist/shopfer'
      artifactName: 'angular-dist'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
